//
// Created by tyran on 2024/8/26.
//

#ifndef TRANSPORT_MACROS_H
#define TRANSPORT_MACROS_H

#define MAC_LENGTH 12
#define ERROR_MESSAGE_LENGTH 2048
#define DEFAULT_FILTER_BUFFER_SIZE 65536
#define DEFAULT_LISTEN_PORT 32999
#define DEFAULT_DEVICE_KEY_WORDS "Netease"
#endif //TRANSPORT_MACROS_H
